project:
  type: website
  output-dir: docs

website:
  site-url: https://wetlandresilienceresearchgroup.github.io
  favicon: "images/logos/Tracking the colour of peatlands.png"
  navbar:
    logo: "images/logos/Tracking the colour of peatlands.png"
    left:
      - index.qmd
      - Research.qmd
      - People.qmd
      - Publications.qmd
      - News.qmd
      - Opportunities.qmd
      - Contact.qmd
      
format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true


# babelquarto:
  # languagecodes:
  # - name: fr
    # text: "Français"
  # - name: en
    # text: "English"
  # mainlanguage: 'en'
  # languages: ['fr']
# description-en: description in en
# author-en: author in en
# lang: en
