project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - images

website:
  navbar:
    left:
      - index.qmd
      - Research.qmd
      - People.qmd
      - Publications.qmd
      - Opportunities.qmd
      - text: "Outreach and presentations"
        href: outreach-presentations.qmd
      - contact.qmd

format:
  html:
    sanitize: false
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true


# babelquarto:
  # languagecodes:
  # - name: fr
    # text: "Français"
  # - name: en
    # text: "English"
  # mainlanguage: 'en'
  # languages: ['fr']
# description-en: description in en
# author-en: author in en
# lang: en
